name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome ${{ github.actor }}! Thank you for adding your first issue to ${{ github.repository }}'' first issue'
        pr-message: 'Thank you ${{ github.actor }} for your first ${{ github.event_name }} at ${{ github.repository }}'' first pr'
